name: flutter_framework_finance_ui
description: "Flutter Framework 金融 UI 扩展层：K 线图、金融语义颜色 Token。"
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_framework_ui:
    path: ../flutter_framework_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
